apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: fx-sinkbinding
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: fx
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: slack-message

