apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: fx-sinkbinding
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: fx
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker 
      name: my-broker
---
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: fy-sinkbinding
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: fy
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker 
      name: my-broker


