apiVersion: messaging.knative.dev/v1
kind: Channel
metadata:
  name: my-channel
  namespace: default
---
apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: slack-message
  namespace: default
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: my-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: slack-message
---
apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: slack-message
  namespace: default
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: my-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: slack-result
